version: '3.8'

# CI/CD override file for integration testing
# Usage: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up

services:
  # Override for CI testing
  db:
    environment:
      POSTGRES_PASSWORD: ci-test-password

  backend:
    image: ${DOCKER_REGISTRY}/${IMAGE_PREFIX}-backend:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    environment:
      NODE_ENV: test
      JWT_SECRET: ci-test-jwt-secret-key
      DATABASE_URL: postgresql://postgres:ci-test-password@db:5432/spheroseg
      REDIS_URL: redis://redis:6379
      ALLOWED_ORIGINS: http://localhost:3000,http://frontend-prod
      LOG_LEVEL: debug

  ml:
    image: ${DOCKER_REGISTRY}/${IMAGE_PREFIX}-ml:${IMAGE_TAG:-latest}
    build:
      context: ./packages/ml
      dockerfile: Dockerfile
    environment:
      DEBUG: true  # Use mock segmentation for CI

  frontend-prod:
    image: ${DOCKER_REGISTRY}/${IMAGE_PREFIX}-frontend:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile.prod

  # Disable services not needed for CI
  frontend-dev:
    profiles: ["disabled"]

  certbot-dev:
    profiles: ["disabled"]

  certbot-prod:
    profiles: ["disabled"]

  adminer:
    profiles: ["disabled"]