FROM node:20-alpine

WORKDIR /app

# Instalace závislostí
COPY frontend/package*.json ./

RUN npm install --legacy-peer-deps

# Kopírování zdrojových souborů
COPY frontend/ ./

# Vystavení portu pro Vite
EXPOSE 8080

# Spuštění vývojového serveru
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
