// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxhlelqkgcozboyftumw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4aGxlbHFrZ2NvemJveWZ0dW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMjA2MjgsImV4cCI6MjA1Mzg5NjYyOH0.-CCeWO62OrtogVYiedjv5GUPnIbsL06kl0sPIOkjWz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);